### ISSUE TITLE
Mac - tilda path expansion doesn't happen

### ISSUE THREAD

**Issue by richie5um** [dufferzafar/cheat#2]
I don't know if it is just my machine, but the tilda path expansion doesn't seem to happen. I had to change my .cheatrc to have a fully qualified path to my cheatsheets folder.

Also, you might want to mention that you need to grab original repo (https://github.com/chrisallenlane/cheat) to actually get the cheatsheets. :-)

Thanks for sharing! I'm learning GoLang too.

**Comment by dufferzafar** [comment]
Thanks for reporting.

I didn't want to handle tilde expansion, simple because go doesn't handle it either, and I wasn't impressed with any of the solutions: http://stackoverflow.com/questions/17609732/expand-tilde-to-home-directory

Though I need to update the readme, to tell people that paths should be full.

Also, I am planning to do something about the cheatsheets. There are a lot of places where you can grab them (not just chris's) - like bro pages, tldr pages etc.

I think I'll create a new repo just for the cheatsheets, and add a command like `cheat fetch` that'll download sheets from the repo. Your thoughts?
